DEBUG 2020-04-19 18:41:41.608 UTC: 	 Running on: Linux lxplus714.cern.ch 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-04-19 18:41:41.626 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-04-19 18:41:41.627 UTC: 	 Executing command: 'submit'
DEBUG 2020-04-19 18:41:41.627 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
DEBUG 2020-04-19 18:41:41.635 UTC: 	 Checking credentials
DEBUG 2020-04-19 18:41:41.635 UTC: 	 Found proxy file /tmp/x509up_u123238
DEBUG 2020-04-19 18:41:41.635 UTC: 	 Getting proxy life time left
DEBUG 2020-04-19 18:41:42.443 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -timeleft
 output : 38036

 error: 
 retcode : 0
DEBUG 2020-04-19 18:41:43.252 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -actimeleft
 output : 38035

 error: 
 retcode : 0
DEBUG 2020-04-19 18:41:43.253 UTC: 	 Proxy lifetime 38036 secs is different from voms extension lifetime 38035 secs for proxy: /tmp/x509up_u123238
DEBUG 2020-04-19 18:41:43.253 UTC: 	 Proxy valid for 10:33:55 hours
ERROR 2020-04-19 18:41:43.253 UTC: 	 CRAB configuration file ./17code/17crabfolder/WWW_4F_TuneCUETP8M1_13TeV-amcatnlo-pythia8.py not found.
ERROR 2020-04-19 18:41:43.253 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file ./17code/17crabfolder/WWW_4F_TuneCUETP8M1_13TeV-amcatnlo-pythia8.py not found.
DEBUG 2020-05-04 14:34:42.063 UTC: 	 Running on: Linux lxplus788.cern.ch 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-04 14:34:42.079 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-05-04 14:34:42.079 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-04 14:34:42.079 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
DEBUG 2020-05-04 14:34:42.087 UTC: 	 Checking credentials
DEBUG 2020-05-04 14:34:42.087 UTC: 	 Found proxy file /tmp/x509up_u123238
DEBUG 2020-05-04 14:34:42.087 UTC: 	 Getting proxy life time left
DEBUG 2020-05-04 14:34:42.692 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -timeleft
 output : 35073

 error: 
 retcode : 0
DEBUG 2020-05-04 14:34:43.299 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -actimeleft
 output : 35072

 error: 
 retcode : 0
DEBUG 2020-05-04 14:34:43.299 UTC: 	 Proxy lifetime 35073 secs is different from voms extension lifetime 35072 secs for proxy: /tmp/x509up_u123238
DEBUG 2020-05-04 14:34:43.299 UTC: 	 Proxy valid for 09:44:32 hours
INFO 2020-05-04 14:34:43.300 UTC: 	 Will use CRAB configuration file ./2016_crab/16crabfolder/WWW_aQGC_miniAOD_v1.py
DEBUG 2020-05-04 14:34:43.300 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-04 14:34:43.305 UTC: 	 Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/afs/cern.ch/work/q/qiguo/B2G/work/04/04_17/16code/MC_signal/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/2016_crab/16_WWW_aQGC_miniAOD_v1_v2.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-04 14:34:43.305 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/SubCommand.py", line 320, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2003/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
[Errno 2] No such file or directory: '/afs/cern.ch/work/q/qiguo/B2G/work/04/04_17/16code/MC_signal/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/2016_crab/16_WWW_aQGC_miniAOD_v1_v2.txt'
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
DEBUG 2020-05-21 15:24:40.785 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-21 15:24:40.785 UTC: 	 Running on: Linux lxplus7103.cern.ch 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-21 15:24:41.074 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-05-21 15:24:41.074 UTC: 	 Executing command: 'checkusername'
DEBUG 2020-05-21 15:24:41.075 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
WARNING 2020-05-21 15:24:41.076 UTC: 	 Warning: 'crab checkusername' command takes no arguments, 1 given. Ignoring arguments ['test_crab.py'].
DEBUG 2020-05-21 15:24:41.086 UTC: 	 Checking credentials
DEBUG 2020-05-21 15:24:41.086 UTC: 	 Found proxy file /tmp/x509up_u123238
DEBUG 2020-05-21 15:24:41.087 UTC: 	 Getting proxy life time left
DEBUG 2020-05-21 15:24:41.793 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -timeleft
 output : 41770

 error: 
 retcode : 0
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Executing : 
 command : voms-proxy-info -file /tmp/x509up_u123238 -actimeleft
 output : 41769

 error: 
 retcode : 0
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Proxy lifetime 41770 secs is different from voms extension lifetime 41769 secs for proxy: /tmp/x509up_u123238
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Proxy valid for 11:36:09 hours
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Command use: checkusername
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Options use: ['test_crab.py']
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Instance is None
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Server base url is None
DEBUG 2020-05-21 15:24:42.499 UTC: 	 Retrieving username ...
DEBUG 2020-05-21 15:24:42.500 UTC: 	 Retrieving username from CRIC...
DEBUG 2020-05-21 15:24:43.645 UTC: 	 username is qiguo
INFO 2020-05-21 15:24:43.646 UTC: 	 Username is: qiguo
DEBUG 2020-05-21 15:24:55.276 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-21 15:24:55.277 UTC: 	 Running on: Linux lxplus7103.cern.ch 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-21 15:24:55.286 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-05-21 15:24:55.286 UTC: 	 Executing command: 'status'
DEBUG 2020-05-21 15:24:55.286 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
ERROR 2020-05-21 15:24:55.287 UTC: 	 Error: test_crab.py is not a valid CRAB project directory.
ERROR 2020-05-21 15:24:55.287 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/status.py", line 41, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 278, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 619, in validateOptions
    raise ConfigurationException(msg)
ConfigurationException: [91mError[0m: test_crab.py is not a valid CRAB project directory.
INFO 2020-05-21 15:24:55.289 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/04/04_17/16code/MC_signal/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
DEBUG 2020-05-21 15:25:06.391 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-05-21 15:25:06.392 UTC: 	 Running on: Linux lxplus7103.cern.ch 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-05-21 15:25:06.400 UTC: 	 OpenSSl version: OpenSSL 1.0.2h  3 May 2016
DEBUG 2020-05-21 15:25:06.401 UTC: 	 Executing command: 'submit'
DEBUG 2020-05-21 15:25:06.401 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
INFO 2020-05-21 15:25:06.402 UTC: 	 Will use CRAB configuration file test_crab.py
DEBUG 2020-05-21 15:25:06.402 UTC: 	 Loading CRAB configuration file.
ERROR 2020-05-21 15:25:06.405 UTC: 	 Error while loading CRAB configuration:
name 'proxy' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2020-05-21 15:25:06.405 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 319, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 88, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
name 'proxy' is not defined
Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3CommonErrors#Syntax_error_in_CRAB_configurati
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2020-05-21 15:25:06.407 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/04/04_17/16code/MC_signal/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
DEBUG 2020-06-07 08:52:22.344 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-06-07 08:52:22.345 UTC: 	 Running on: Linux lxplus706.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-06-07 08:52:22.359 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-06-07 08:52:22.360 UTC: 	 Executing command: 'submit'
DEBUG 2020-06-07 08:52:22.360 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
ERROR 2020-06-07 08:52:22.387 UTC: 	 CRAB configuration file 2016_crab/16crabfolder/ not found.
ERROR 2020-06-07 08:52:22.387 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 319, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/3.3.2005/lib/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file 2016_crab/16crabfolder/ not found.
INFO 2020-06-07 08:52:22.422 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/04/04_17/16code/MC_signal/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
DEBUG 2020-06-28 13:50:20.724 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-06-28 13:50:20.724 UTC: 	 Running on: Linux lxplus755.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-06-28 13:50:20.741 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-06-28 13:50:20.741 UTC: 	 Executing command: 'submit'
DEBUG 2020-06-28 13:50:20.742 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
ERROR 2020-06-28 13:50:20.751 UTC: 	 CRAB configuration file WWW_aQGC_miniAOD_v1.py not found.
ERROR 2020-06-28 13:50:20.752 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 319, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file WWW_aQGC_miniAOD_v1.py not found.
INFO 2020-06-28 13:50:20.761 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/06/06_28/test/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
DEBUG 2020-07-02 12:56:38.699 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-02 12:56:38.699 UTC: 	 Running on: Linux lxplus721.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-02 12:56:38.714 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-02 12:56:38.714 UTC: 	 Executing command: 'submit'
DEBUG 2020-07-02 12:56:38.715 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
ERROR 2020-07-02 12:56:38.734 UTC: 	 CRAB configuration file WWW_aQGC_miniAOD_v1.py not found.
ERROR 2020-07-02 12:56:38.734 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 319, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 50, in loadConfig
    raise ConfigurationException("CRAB configuration file %s not found." % (configname))
ConfigurationException: CRAB configuration file WWW_aQGC_miniAOD_v1.py not found.
INFO 2020-07-02 12:56:38.750 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/06/06_28/test/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
DEBUG 2020-07-02 12:57:39.387 UTC: 	 CRAB Client version: 3.3.2005
DEBUG 2020-07-02 12:57:39.387 UTC: 	 Running on: Linux lxplus721.cern.ch 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2020-07-02 12:57:39.402 UTC: 	 OpenSSl version: OpenSSL 1.0.2k-fips  26 Jan 2017 (Library: OpenSSL 1.0.2d-fips 9 Jul 2015)
DEBUG 2020-07-02 12:57:39.402 UTC: 	 Executing command: 'submit'
DEBUG 2020-07-02 12:57:39.402 UTC: 	 Found CRAB cache file /afs/cern.ch/user/q/qiguo/.crab3
INFO 2020-07-02 12:57:39.403 UTC: 	 Will use CRAB configuration file 2016_crab/16crabfolder/WWW_aQGC_miniAOD_v1.py
DEBUG 2020-07-02 12:57:39.403 UTC: 	 Loading CRAB configuration file.
DEBUG 2020-07-02 12:57:39.947 UTC: 	 Will use CRAB Analysis plugin (i.e. will run an analysis job type).
ERROR 2020-07-02 12:57:39.948 UTC: 	 Working area '/afs/cern.ch/work/q/qiguo/B2G/work/06/06_28/test/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab_16_WWW_aQGC_miniAOD_v1_v9' already exists 
Please change the requestName in the config file
ERROR 2020-07-02 12:57:39.948 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 165, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/bin/crab", line 150, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/submit.py", line 35, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/Commands/SubCommand.py", line 323, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.2005.01/lib/CRABClient/ClientUtilities.py", line 407, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/work/q/qiguo/B2G/work/06/06_28/test/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab_16_WWW_aQGC_miniAOD_v1_v9' already exists 
Please change the requestName in the config file
INFO 2020-07-02 12:57:39.953 UTC: 	 Log file is /afs/cern.ch/work/q/qiguo/B2G/work/06/06_28/test/CMSSW_10_2_18/src/ExoDiBosonResonances/EDBRTreeMaker/test/crab.log
